/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.superadmin.gestion_usuarios;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

import com.mycompany.primera_practica_codigo.modelo.dao.SucursalDAO;
import com.mycompany.primera_practica_codigo.modelo.dao.UsuarioDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Rol;
import com.mycompany.primera_practica_codigo.modelo.entidades.Sucursal;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;
import com.mycompany.primera_practica_codigo.vista.MensajeExitoFrame;
import com.mycompany.primera_practica_codigo.vista.superadmin.FrameInicioSuperAdministrador;

/**
 *
 * @author Matul
 */
public class FrameAsignarSucursal extends javax.swing.JFrame {

    private final String SUPER_ADMINISTRADOR = "admin";

    /**
     * Creates new form FrameAsignarSucursal
     */
    public FrameAsignarSucursal() {
        initComponents();
        setLocationRelativeTo(null);

        limpiarCampos();
        cargarUsuarios();
        cargarSucursales();
        cargarRoles();
    }

    private void limpiarCampos() {
        // Limpiar las opciones de los JComboBox
        jComboBoxUsuarios.removeAllItems();
        jComboBoxSucursales.removeAllItems();
        jComboBoxRoles.removeAllItems();
    }

    private void cargarUsuarios() {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        List<Usuario> usuarios = null;
        try {
            usuarios = usuarioDAO.obtenerTodo();
        } catch (SQLException e) {
            String mensaje = "Error al cargar los usuarios: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
        }
        if (usuarios != null) {
            for (Usuario usuario : usuarios) {
                if (!usuario.getNombreUsuario().equals(SUPER_ADMINISTRADOR)) {
                    jComboBoxUsuarios.addItem(usuario.getNombreUsuario());
                }
            }
        }
    }

    private void cargarSucursales() {
        SucursalDAO sucursalDAO = new SucursalDAO();
        List<Sucursal> sucursales = null;
        try {
            sucursales = sucursalDAO.obtenerTodo();
        } catch (SQLException e) {
            String mensaje = "Error al cargar las sucursales: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
        }
        if (sucursales != null) {
            for (Sucursal sucursal : sucursales) {
                jComboBoxSucursales.addItem(sucursal.getNombre());
            }
        }
    }

    private void cargarRoles() {
        jComboBoxRoles.addItem("Administrador Sucursal");
        jComboBoxRoles.addItem("Jugador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBuscarEditarSucursal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jComboBoxSucursales = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jComboBoxRoles = new javax.swing.JComboBox<>();
        jButtonAsignar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonRegresar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabelBuscarEditarSucursal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelBuscarEditarSucursal.setText("Asignar sucursal a usuario");
        jPanel2.add(jLabelBuscarEditarSucursal);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

        jPanel9.setLayout(new java.awt.GridLayout(0, 1));

        jComboBoxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBoxUsuarios);

        jPanel5.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(0, 1));

        jComboBoxSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBoxSucursales);

        jPanel5.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(0, 1));

        jComboBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel11.add(jComboBoxRoles);

        jPanel5.add(jPanel11);

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAsignar);

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel7);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel20.add(jButtonRegresar);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel8);

        jPanel17.add(jPanel20);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18);

        jPanel1.add(jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAsignarActionPerformed
        String nombreUsuario = (String) jComboBoxUsuarios.getSelectedItem();
        String nombreSucursal = (String) jComboBoxSucursales.getSelectedItem();
        Rol rolSeleccionado = obtenerRolSeleccionado();

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        SucursalDAO sucursalDAO = new SucursalDAO();

        try {
            Optional<Usuario> usuario = usuarioDAO.encontrarPorNombre(nombreUsuario);
            Optional<Sucursal> sucursal = sucursalDAO.encontrarPorNombre(nombreSucursal);

            if (usuario.isPresent() && sucursal.isPresent()) {
                usuario.get().setSucursal(sucursal.get());
                usuario.get().setRol(rolSeleccionado);
                usuarioDAO.actualizar(usuario.get());
                String mensaje = "Sucursal asignada exitosamente al usuario.";
                MensajeExitoFrame mensajeExitoFrame = new MensajeExitoFrame(null, true, mensaje);
            } else {
                String mensaje = "Error: Usuario o sucursal no encontrados.";
                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
            }
        } catch (SQLException e) {
            String mensaje = "Error al asignar la sucursal: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
        }
    }// GEN-LAST:event_jButtonAsignarActionPerformed

    private Rol obtenerRolSeleccionado() {
        String rolSeleccionado = (String) jComboBoxRoles.getSelectedItem();
        if ("Administrador Sucursal".equals(rolSeleccionado)) {
            return Rol.ADMINISTRADOR_SUCURSAL;
        } else if ("Jugador".equals(rolSeleccionado)) {
            return Rol.JUGADOR;
        } else {
            throw new IllegalArgumentException("Rol desconocido: " + rolSeleccionado);
        }
    }

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        FrameInicioSuperAdministrador frameGestionUsuarios = new FrameInicioSuperAdministrador();
        frameGestionUsuarios.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxRoles;
    private javax.swing.JComboBox<String> jComboBoxSucursales;
    private javax.swing.JComboBox<String> jComboBoxUsuarios;
    private javax.swing.JLabel jLabelBuscarEditarSucursal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
