/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.superadmin.parametros;

import java.sql.SQLException;

import javax.swing.SpinnerNumberModel;

import com.mycompany.primera_practica_codigo.modelo.dao.ConfiguracionJuegoDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.ConfiguracionJuego;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;
import com.mycompany.primera_practica_codigo.vista.superadmin.FrameInicioSuperAdministrador;

/**
 *
 * @author Matul
 */
public class FrameParametros extends javax.swing.JFrame {

    private final int MIN_SEGUNDOS_POR_PEDIDO_NIVEL_1 = 10;
    private final int MIN_SEGUNDOS_POR_PEDIDO_NIVEL_2 = 7;
    private final int MIN_SEGUNDOS_POR_PEDIDO_NIVEL_3 = 5;
    private final int MIN_MAXIMO_DE_PEDIDOS_ACTIVOS = 4;
    private final int MIN_DURACION_TURNO = 60;
    private final int MIN_PUNTOS_PARA_SUBIR_NIVEL_2 = 50;
    private final int MIN_PUNTOS_PARA_SUBIR_NIVEL_3 = 80;
    private ConfiguracionJuego configuracion;
    private int segundosPorPedidosNivel1;
    private int segundosPorPedidosNivel2;
    private int segundosPorPedidosNivel3;
    private int maximoDePedidosActivos;
    private int duracionTurno;
    private int puntosParaSubirNivel2;
    private int puntosParaSubirNivel3;

    /**
     * Creates new form FrameParametros
     */
    public FrameParametros() {
        initComponents();
        setLocationRelativeTo(null);
        cargarValores();
        definirConfiguracionInicial();
    }

    private void cargarValores() {
        this.configuracion = new ConfiguracionJuego();
        ConfiguracionJuegoDAO configuracionDAO = new ConfiguracionJuegoDAO();

        try {
            configuracion = configuracionDAO.obtenerConfiguracion();
        } catch (SQLException e) {
            String mensajeError = "Error al cargar la configuración del juego: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
            this.dispose();
        }
        segundosPorPedidosNivel1 = configuracion.getSegundosPorPedidosNivel1();
        segundosPorPedidosNivel2 = configuracion.getSegundosPorPedidosNivel2();
        segundosPorPedidosNivel3 = configuracion.getSegundosPorPedidosNivel3();
        maximoDePedidosActivos = configuracion.getMaximoDePedidosActivos();
        duracionTurno = configuracion.getDuracionTurno();
        puntosParaSubirNivel2 = configuracion.getPuntosParaSubirNivel2();
        puntosParaSubirNivel3 = configuracion.getPuntosParaSubirNivel3();
    }

    private void definirConfiguracionInicial() {
        SpinnerNumberModel modelSegNivel1 = new SpinnerNumberModel(segundosPorPedidosNivel1,
                MIN_SEGUNDOS_POR_PEDIDO_NIVEL_1, null, 1);
        jSpinnerSegPedidosNivel1.setModel(modelSegNivel1);
        SpinnerNumberModel modelSegNivel2 = new SpinnerNumberModel(segundosPorPedidosNivel2,
                MIN_SEGUNDOS_POR_PEDIDO_NIVEL_2, null, 1);
        jSpinnerSegPedidosNivel2.setModel(modelSegNivel2);
        SpinnerNumberModel modelSegNivel3 = new SpinnerNumberModel(segundosPorPedidosNivel3,
                MIN_SEGUNDOS_POR_PEDIDO_NIVEL_3, null, 1);
        jSpinnerSegPedidosNivel3.setModel(modelSegNivel3);
        SpinnerNumberModel modelMaxPedidosActivos = new SpinnerNumberModel(maximoDePedidosActivos,
                MIN_MAXIMO_DE_PEDIDOS_ACTIVOS, null, 1);
        jSpinnerMaxPedidosActivos.setModel(modelMaxPedidosActivos);
        SpinnerNumberModel modelDuracionTurno = new SpinnerNumberModel(duracionTurno, MIN_DURACION_TURNO, null, 1);
        jSpinnerDuracionTurno.setModel(modelDuracionTurno);
        SpinnerNumberModel modelPuntosParaSubirNivel2 = new SpinnerNumberModel(puntosParaSubirNivel2,
                MIN_PUNTOS_PARA_SUBIR_NIVEL_2, null, 1);
        jSpinnerPuntosParaSubirNivel2.setModel(modelPuntosParaSubirNivel2);
        SpinnerNumberModel modelPuntosParaSubirNivel3 = new SpinnerNumberModel(puntosParaSubirNivel3,
                MIN_PUNTOS_PARA_SUBIR_NIVEL_3, null, 1);
        jSpinnerPuntosParaSubirNivel3.setModel(modelPuntosParaSubirNivel3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelSegundosNivel1Title = new javax.swing.JLabel();
        jLabelSegundosNivel2Title = new javax.swing.JLabel();
        jLabelSegundosNivel3Title = new javax.swing.JLabel();
        jLabelMaxPedidosActivosTitle = new javax.swing.JLabel();
        jLabelDuracionTurnoTitle = new javax.swing.JLabel();
        jLabelPuntosParaSubirNivel2Title = new javax.swing.JLabel();
        jLabelPuntosParaSubirNivel3Title = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSpinnerSegPedidosNivel1 = new javax.swing.JSpinner();
        jSpinnerSegPedidosNivel2 = new javax.swing.JSpinner();
        jSpinnerSegPedidosNivel3 = new javax.swing.JSpinner();
        jSpinnerMaxPedidosActivos = new javax.swing.JSpinner();
        jSpinnerDuracionTurno = new javax.swing.JSpinner();
        jSpinnerPuntosParaSubirNivel2 = new javax.swing.JSpinner();
        jSpinnerPuntosParaSubirNivel3 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonAplicarCambios = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setText("Parametros del Juego");
        jPanel5.add(jLabelTitle);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 242, Short.MAX_VALUE));

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelSegundosNivel1Title.setText("Segundos por pedido Nivel 1 (Min. 10s)");
        jPanel7.add(jLabelSegundosNivel1Title);

        jLabelSegundosNivel2Title.setText("Segundos por pedido Nivel 2 (Min. 7s)");
        jPanel7.add(jLabelSegundosNivel2Title);

        jLabelSegundosNivel3Title.setText("Segundos por pedido Nivel 3 (Min. 5 seg)");
        jPanel7.add(jLabelSegundosNivel3Title);

        jLabelMaxPedidosActivosTitle.setText("Maximo de pedidos activos (Min. 4)");
        jPanel7.add(jLabelMaxPedidosActivosTitle);

        jLabelDuracionTurnoTitle.setText("Duracion de turno (segundos, Min. 60s)");
        jPanel7.add(jLabelDuracionTurnoTitle);

        jLabelPuntosParaSubirNivel2Title.setText("Puntos para subir a Nivel 2 (Min. 50pts)");
        jPanel7.add(jLabelPuntosParaSubirNivel2Title);

        jLabelPuntosParaSubirNivel3Title.setText("Puntos para subier a nivel  (Min. 80 pts)");
        jPanel7.add(jLabelPuntosParaSubirNivel3Title);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jPanel8.add(jSpinnerSegPedidosNivel1);
        jPanel8.add(jSpinnerSegPedidosNivel2);
        jPanel8.add(jSpinnerSegPedidosNivel3);
        jPanel8.add(jSpinnerMaxPedidosActivos);
        jPanel8.add(jSpinnerDuracionTurno);
        jPanel8.add(jSpinnerPuntosParaSubirNivel2);
        jPanel8.add(jSpinnerPuntosParaSubirNivel3);

        jPanel3.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 242, Short.MAX_VALUE));

        jPanel3.add(jPanel9);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jPanel4.add(jLabel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jPanel10.add(jLabel12);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonRegresar);

        jButtonAplicarCambios.setText("Aplicar cambios");
        jButtonAplicarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarCambiosActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonAplicarCambios);
        jPanel10.add(jLabel11);

        jPanel4.add(jPanel10);
        jPanel4.add(jLabel10);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAplicarCambiosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAplicarCambiosActionPerformed
        recolectarDatosSpinners();
        ConfiguracionJuegoDAO configuracionDAO = new ConfiguracionJuegoDAO();
        try {
            configuracionDAO.actualizarConfiguracion(configuracion);
            String mensajeExito = "Configuración actualizada exitosamente.";
            MensajeErrorFrame mensajeExitoFrame = new MensajeErrorFrame(null, true, mensajeExito);
        } catch (

        SQLException e) {
            String mensajeError = "Error al actualizar la configuración del juego: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
        }

    }// GEN-LAST:event_jButtonAplicarCambiosActionPerformed

    private void recolectarDatosSpinners() {

        segundosPorPedidosNivel1 = (int) jSpinnerSegPedidosNivel1.getValue();
        segundosPorPedidosNivel2 = (int) jSpinnerSegPedidosNivel2.getValue();
        segundosPorPedidosNivel3 = (int) jSpinnerSegPedidosNivel3.getValue();
        maximoDePedidosActivos = (int) jSpinnerMaxPedidosActivos.getValue();
        duracionTurno = (int) jSpinnerDuracionTurno.getValue();
        puntosParaSubirNivel2 = (int) jSpinnerPuntosParaSubirNivel2.getValue();
        puntosParaSubirNivel3 = (int) jSpinnerPuntosParaSubirNivel3.getValue();

        configuracion.setSegundosPorPedidosNivel1(segundosPorPedidosNivel1);
        configuracion.setSegundosPorPedidosNivel2(segundosPorPedidosNivel2);
        configuracion.setSegundosPorPedidosNivel3(segundosPorPedidosNivel3);
        configuracion.setMaximoDePedidosActivos(maximoDePedidosActivos);
        configuracion.setDuracionTurno(duracionTurno);
        configuracion.setPuntosParaSubirNivel2(puntosParaSubirNivel2);
        configuracion.setPuntosParaSubirNivel3(puntosParaSubirNivel3);
    }

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        FrameInicioSuperAdministrador frameInicioSuperAdministrador = new FrameInicioSuperAdministrador();
        frameInicioSuperAdministrador.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicarCambios;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDuracionTurnoTitle;
    private javax.swing.JLabel jLabelMaxPedidosActivosTitle;
    private javax.swing.JLabel jLabelPuntosParaSubirNivel2Title;
    private javax.swing.JLabel jLabelPuntosParaSubirNivel3Title;
    private javax.swing.JLabel jLabelSegundosNivel1Title;
    private javax.swing.JLabel jLabelSegundosNivel2Title;
    private javax.swing.JLabel jLabelSegundosNivel3Title;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpinnerDuracionTurno;
    private javax.swing.JSpinner jSpinnerMaxPedidosActivos;
    private javax.swing.JSpinner jSpinnerPuntosParaSubirNivel2;
    private javax.swing.JSpinner jSpinnerPuntosParaSubirNivel3;
    private javax.swing.JSpinner jSpinnerSegPedidosNivel1;
    private javax.swing.JSpinner jSpinnerSegPedidosNivel2;
    private javax.swing.JSpinner jSpinnerSegPedidosNivel3;
    // End of variables declaration//GEN-END:variables
}
