/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista;

import java.util.Optional;

import com.mycompany.primera_practica_codigo.modelo.dao.UsuarioDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Rol;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.FrameInicioAdministradorSucursal;
import com.mycompany.primera_practica_codigo.vista.juego.FrameInicioJugador;
import com.mycompany.primera_practica_codigo.vista.superadmin.FrameInicioSuperAdministrador;

/**
 *
 * @author brayanth
 */
public class FrameLogin extends javax.swing.JFrame {

        /**
         * Creates new form FrameLogin
         */
        public FrameLogin() {
                initComponents();
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jLabelTtle = new javax.swing.JLabel();
                jLabelUsuario = new javax.swing.JLabel();
                jTextFieldUsuario = new javax.swing.JTextField();
                jLabelUsuarioPassword = new javax.swing.JLabel();
                jPasswordFieldPassword = new javax.swing.JPasswordField();
                bottonLogin = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setLayout(new java.awt.GridLayout(1, 0));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 346, Short.MAX_VALUE));

                jPanel1.add(jPanel2);

                jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 15));
                jPanel3.add(jPanel7);

                jLabelTtle.setFont(new java.awt.Font("Greconian", 0, 18)); // NOI18N
                jLabelTtle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelTtle.setText("Pizza Express Tycoon");
                jPanel5.add(jLabelTtle);

                jPanel3.add(jPanel5);

                jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelUsuario.setText("Usuario");
                jPanel3.add(jLabelUsuario);
                jPanel3.add(jTextFieldUsuario);

                jLabelUsuarioPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelUsuarioPassword.setText("Contraseña");
                jPanel3.add(jLabelUsuarioPassword);
                jPanel3.add(jPasswordFieldPassword);

                bottonLogin.setText("Iniciar Sesion");
                bottonLogin.addActionListener(this::bottonLoginActionPerformed);
                jPanel3.add(bottonLogin);

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 223, Short.MAX_VALUE));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 30, Short.MAX_VALUE));

                jPanel3.add(jPanel6);

                jPanel1.add(jPanel3);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 346, Short.MAX_VALUE));

                jPanel1.add(jPanel4);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void validarCredenciales() {

                String usuarioNombre = jTextFieldUsuario.getText();
                String password = new String(jPasswordFieldPassword.getPassword());
                UsuarioDAO usuarioDAO = new UsuarioDAO();

                try {
                        Optional<Usuario> usuario = usuarioDAO.encontrarPorNombre(usuarioNombre);
                        if (usuario.isPresent() && usuario.get().getPassword().equals(password)) {

                                Usuario usuarioLogeado = usuario.get();
                                // Credenciales válidas, abrir la ventana principal
                                if (usuario.get().getRol() == Rol.JUGADOR) {
                                        FrameInicioJugador frameInicioJugador = new FrameInicioJugador(usuarioLogeado);
                                        frameInicioJugador.setVisible(true);
                                        this.dispose();
                                } else if (usuario.get().getRol() == Rol.ADMINISTRADOR_SUCURSAL) {
                                        FrameInicioAdministradorSucursal adminSucursal = new FrameInicioAdministradorSucursal(
                                                        usuarioLogeado);

                                        adminSucursal.setVisible(true);
                                        this.dispose();

                                } else if (usuario.get().getRol() == Rol.SUPERADMINISTRADOR) {
                                        FrameInicioSuperAdministrador frame = new FrameInicioSuperAdministrador();
                                        frame.setVisible(true);
                                        this.dispose();
                                }
                        } else {
                                String mensajeError = "Usuario o contraseña incorrectos.";
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                        }
                } catch (Exception e) {
                        String mensajeError = "Error al validar credenciales: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }

        }

        private void bottonLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bottonLoginActionPerformed
                validarCredenciales();
        }// GEN-LAST:event_bottonLoginActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bottonLogin;
        private javax.swing.JLabel jLabelTtle;
        private javax.swing.JLabel jLabelUsuario;
        private javax.swing.JLabel jLabelUsuarioPassword;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPasswordField jPasswordFieldPassword;
        private javax.swing.JTextField jTextFieldUsuario;
        // End of variables declaration//GEN-END:variables
}
