/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista;

/**
 *
 * @author Matul
 */
public class MensajeExitoFrame extends javax.swing.JDialog {

    
    private String mensajeExito;
    
    /**
     * Creates new form MensajeErrorFrame
     */
    public MensajeExitoFrame(java.awt.Frame parent, boolean modal, String mensajeExito) {
        super(parent, modal);
        initComponents();
        this.mensajeExito = mensajeExito;
        jlblMensajeError.setText(mensajeExito);
        
        setSize(500, 150);
        setLocationRelativeTo(null);
        setVisible(true);
        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelElementos = new javax.swing.JPanel();
        jlblMensajeError = new javax.swing.JLabel();
        jbuttonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelElementos.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        jlblMensajeError.setText("Mensaje de Error");
        panelElementos.add(jlblMensajeError);

        jbuttonAceptar.setText("Aceptar");
        jbuttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAceptarActionPerformed(evt);
            }
        });
        panelElementos.add(jbuttonAceptar);

        panelPrincipal.add(panelElementos);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_jbuttonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuttonAceptar;
    private javax.swing.JLabel jlblMensajeError;
    private javax.swing.JPanel panelElementos;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
