/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.superadmin;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.mycompany.primera_practica_codigo.modelo.dao.EstadisticaGlobalDAO;
import com.mycompany.primera_practica_codigo.modelo.dao.SucursalDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Sucursal;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;

/**
 *
 * @author Matul
 */
public class FrameEstadisticasGlobales extends javax.swing.JFrame {

        private List<PanelEstadisticaSucursal> panelesSucursales;
        private List<Sucursal> sucursales;
        private int partidasJugadasGlobales;
        private int pedidosEntregadosGlobales;
        private int pedidosCanceladosGlobales;
        private int pedidosNoEntregadosGlobales;

        /**
         * Creates new form FrameEstadisticasGlobales
         */
        public FrameEstadisticasGlobales() {
                initComponents();
                setLocationRelativeTo(null);
                cargarDatosSucursales();
                generarListadoJPanels();
                cargarDatosGlobales();
                cargarDatosSucursalEnComboBox();
                mostrarEstadisticaSucursalSeleccionada();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jComboBoxSucursales = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                jPanelEstidisticaSucursal = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jPanel10 = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jPanel11 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabelTitlePartidas = new javax.swing.JLabel();
                jLabelPuntajeAcumuladoTitle = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jPanel12 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabelPartidasJugadas = new javax.swing.JLabel();
                jLabelPedidosEntregados = new javax.swing.JLabel();
                jLabelPedidosCancelados = new javax.swing.JLabel();
                jLabelNoEntregados = new javax.swing.JLabel();
                jPanel14 = new javax.swing.JPanel();
                jPanel15 = new javax.swing.JPanel();
                jPanel16 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jButtonRegresar = new javax.swing.JButton();
                jLabel9 = new javax.swing.JLabel();
                jPanel17 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setLayout(new java.awt.GridLayout(0, 1));

                jPanel2.setLayout(new java.awt.GridLayout(0, 1));

                jPanel5.setLayout(new java.awt.BorderLayout());

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Estadisticas Globales");
                jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

                jPanel2.add(jPanel5);

                jPanel6.setLayout(new java.awt.GridLayout(1, 0));

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 192, Short.MAX_VALUE));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 104, Short.MAX_VALUE));

                jPanel6.add(jPanel7);

                jPanel8.setLayout(new java.awt.GridLayout(0, 1));
                jPanel8.add(jLabel12);
                jPanel8.add(jLabel2);

                jComboBoxSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jComboBoxSucursales.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxSucursalesActionPerformed(evt);
                        }
                });
                jPanel8.add(jComboBoxSucursales);
                jPanel8.add(jLabel3);

                jPanel6.add(jPanel8);

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 192, Short.MAX_VALUE));
                jPanel9Layout.setVerticalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 104, Short.MAX_VALUE));

                jPanel6.add(jPanel9);

                jPanel2.add(jPanel6);

                jPanel1.add(jPanel2);

                jPanelEstidisticaSucursal.setLayout(new java.awt.GridLayout());
                jPanel1.add(jPanelEstidisticaSucursal);

                jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

                jLabel8.setText("SUMATORIA DE DATOS DE SUCURSAL");
                jPanel4.add(jLabel8);

                jPanel10.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

                jPanel13.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

                jPanel11.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
                jPanel11.add(jLabel6);

                jLabelTitlePartidas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabelTitlePartidas.setText("Total partidas Jugadas");
                jPanel11.add(jLabelTitlePartidas);

                jLabelPuntajeAcumuladoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabelPuntajeAcumuladoTitle.setText("Pedidos Entregados");
                jPanel11.add(jLabelPuntajeAcumuladoTitle);

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel4.setText("Pedidos Cancelados");
                jPanel11.add(jLabel4);

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel5.setText("Pedidos No Entregados");
                jPanel11.add(jLabel5);

                jPanel13.add(jPanel11);

                jPanel12.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
                jPanel12.add(jLabel7);

                jLabelPartidasJugadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelPartidasJugadas.setText("00");
                jPanel12.add(jLabelPartidasJugadas);

                jLabelPedidosEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelPedidosEntregados.setText("00");
                jPanel12.add(jLabelPedidosEntregados);

                jLabelPedidosCancelados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelPedidosCancelados.setText("00");
                jPanel12.add(jLabelPedidosCancelados);

                jLabelNoEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelNoEntregados.setText("00");
                jPanel12.add(jLabelNoEntregados);

                jPanel13.add(jPanel12);

                jPanel10.add(jPanel13);

                jPanel4.add(jPanel10);

                jPanel14.setLayout(new java.awt.GridLayout(1, 0));

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 192, Short.MAX_VALUE));
                jPanel15Layout.setVerticalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanel14.add(jPanel15);

                jPanel16.setLayout(new java.awt.GridLayout(0, 1));
                jPanel16.add(jLabel10);

                jButtonRegresar.setText("Regresar");
                jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRegresarActionPerformed(evt);
                        }
                });
                jPanel16.add(jButtonRegresar);
                jPanel16.add(jLabel9);

                jPanel14.add(jPanel16);

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 192, Short.MAX_VALUE));
                jPanel17Layout.setVerticalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanel14.add(jPanel17);

                jPanel4.add(jPanel14);

                jPanel1.add(jPanel4);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void generarListadoJPanels() {
                int nivelMaxSucursal;
                int partidasJugadas;
                int pedidosEntregados;
                int pedidosCancelados;
                int pedidosNoEntregados;
                String nombreSucursal;
                panelesSucursales = new ArrayList<>();
                EstadisticaGlobalDAO estadisticaGlobalDAO = new EstadisticaGlobalDAO();
                int idSucursal = 0;

                for (Sucursal sucursal : sucursales) {
                        idSucursal = sucursal.getId();
                        nombreSucursal = sucursal.getNombre();
                        try {
                                nivelMaxSucursal = estadisticaGlobalDAO.nivelMaximoAlcanzadoPorSucursal(idSucursal);
                                partidasJugadas = estadisticaGlobalDAO.totalPartidasJugadasPorSucursal(idSucursal);
                                pedidosEntregados = estadisticaGlobalDAO.totalPedidosEntregadosPorSucursal(idSucursal);
                                pedidosCancelados = estadisticaGlobalDAO.totalPedidosCanceladosPorSucursal(idSucursal);
                                pedidosNoEntregados = estadisticaGlobalDAO
                                                .totalPedidosNoEntregadosPorSucursal(idSucursal);
                                PanelEstadisticaSucursal panel = new PanelEstadisticaSucursal(
                                                nivelMaxSucursal, partidasJugadas, pedidosEntregados, pedidosCancelados,
                                                pedidosNoEntregados, nombreSucursal);
                                panelesSucursales.add(panel);
                        } catch (SQLException e) {
                                String mensajeError = "Error al cargar los datos de la sucursal: " + e.getMessage();
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                        }
                }
        }

        private void cargarDatosGlobales() {
                EstadisticaGlobalDAO estadisticaGlobalDAO = new EstadisticaGlobalDAO();
                try {
                        partidasJugadasGlobales = estadisticaGlobalDAO.totalPartidasJugadas();
                        pedidosEntregadosGlobales = estadisticaGlobalDAO.totalPedidosEntregados();
                        pedidosCanceladosGlobales = estadisticaGlobalDAO.totalPedidosCancelados();
                        pedidosNoEntregadosGlobales = estadisticaGlobalDAO.totalPedidosNoEntregados();
                        jLabelPartidasJugadas.setText(String.valueOf(partidasJugadasGlobales));
                        jLabelPedidosEntregados.setText(String.valueOf(pedidosEntregadosGlobales));
                        jLabelPedidosCancelados.setText(String.valueOf(pedidosCanceladosGlobales));
                        jLabelNoEntregados.setText(String.valueOf(pedidosNoEntregadosGlobales));
                } catch (SQLException e) {
                        String mensajeError = "Error al cargar los datos globales: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }
        }

        private void cargarDatosSucursales() {
                SucursalDAO sucursalDAO = new SucursalDAO();
                try {
                        sucursales = sucursalDAO.obtenerTodo();
                } catch (SQLException e) {
                        String mensajeError = "Error al cargar los datos de la sucursal: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }
        }

        private void cargarDatosSucursalEnComboBox() {
                jComboBoxSucursales.removeAllItems();
                for (Sucursal sucursal : sucursales) {
                        jComboBoxSucursales.addItem(sucursal.getNombre());
                }
        }

        private String obtenerNombreSucursalSeleccionada() {
                int indiceSeleccionado = jComboBoxSucursales.getSelectedIndex();
                if (indiceSeleccionado >= 0 && indiceSeleccionado < sucursales.size()) {
                        return sucursales.get(indiceSeleccionado).getNombre();
                }
                return null;
        }

        private void mostrarEstadisticaSucursalSeleccionada() {
                String nombreSucursalSeleccionada = obtenerNombreSucursalSeleccionada();
                for (PanelEstadisticaSucursal panel : panelesSucursales) {
                        if (panel.getNombreSucursal().equals(nombreSucursalSeleccionada)) {
                                jPanelEstidisticaSucursal.removeAll();
                                jPanelEstidisticaSucursal.add(panel);
                                jPanelEstidisticaSucursal.revalidate();
                                jPanelEstidisticaSucursal.repaint();
                                System.out.println("Mostrando estadísticas para la sucursal: "
                                                + nombreSucursalSeleccionada);
                                break;
                        }
                }
        }

        private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
                FrameInicioSuperAdministrador frameInicioSuperAdministrador = new FrameInicioSuperAdministrador();
                frameInicioSuperAdministrador.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButtonRegresarActionPerformed

        private void jComboBoxSucursalesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxSucursalesActionPerformed
                mostrarEstadisticaSucursalSeleccionada();
        }// GEN-LAST:event_jComboBoxSucursalesActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonRegresar;
        private javax.swing.JComboBox<String> jComboBoxSucursales;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLabel jLabelNoEntregados;
        private javax.swing.JLabel jLabelPartidasJugadas;
        private javax.swing.JLabel jLabelPedidosCancelados;
        private javax.swing.JLabel jLabelPedidosEntregados;
        private javax.swing.JLabel jLabelPuntajeAcumuladoTitle;
        private javax.swing.JLabel jLabelTitlePartidas;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JPanel jPanelEstidisticaSucursal;
        // End of variables declaration//GEN-END:variables
}
