/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.superadmin;

import com.mycompany.primera_practica_codigo.modelo.dao.SucursalDAO;
import com.mycompany.primera_practica_codigo.modelo.dao.UsuarioDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Sucursal;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.FrameLogin;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestionSucursales.FrameBuscadorSucursal;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestionSucursales.FrameEditorSucursal;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestionSucursales.FrameListaSucursales;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestion_usuarios.FrameAsignarSucursal;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestion_usuarios.FrameBuscadorUsuario;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestion_usuarios.FrameEditorUsuario;
import com.mycompany.primera_practica_codigo.vista.superadmin.gestion_usuarios.FrameListaUsuarios;

import java.sql.SQLException;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brayanth
 */
public class FrameInicioSuperAdministrador extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(FrameInicioSuperAdministrador.class.getName());

        /**
         * Creates new form FrameInicioSuperAdministrador
         */
        public FrameInicioSuperAdministrador() {
                initComponents();
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabelNombreTycoon = new javax.swing.JLabel();
                jLabelSuperadministrador = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel10 = new javax.swing.JPanel();
                jPanel9 = new javax.swing.JPanel();
                jLabelGestionSucursales = new javax.swing.JLabel();
                jButtonCrearNuevaSucursal = new javax.swing.JButton();
                jButtonEditarSucursalExistente = new javax.swing.JButton();
                jButtonListaSucursales = new javax.swing.JButton();
                jPanel11 = new javax.swing.JPanel();
                jLabelGestionUsuarios = new javax.swing.JLabel();
                jButtonRegistroUsuario = new javax.swing.JButton();
                jButtonModificarUsuario = new javax.swing.JButton();
                jButtonAsignarUsurioASucursal = new javax.swing.JButton();
                jButtonListaUsuarios = new javax.swing.JButton();
                jPanel8 = new javax.swing.JPanel();
                jPanel12 = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jPanel14 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jButtonEstadisticasGlobales = new javax.swing.JButton();
                jButtonRankingJugadores = new javax.swing.JButton();
                jPanel15 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jButtonParametrosJuego = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jPanel16 = new javax.swing.JPanel();
                jPanel17 = new javax.swing.JPanel();
                jPanel19 = new javax.swing.JPanel();
                jPanel20 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jButtonCerrarSesion = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                jPanel18 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

                jPanel2.setLayout(new java.awt.GridLayout(0, 1));

                jLabelNombreTycoon.setFont(new java.awt.Font("Greconian", 0, 18)); // NOI18N
                jLabelNombreTycoon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelNombreTycoon.setText("Pizza Express Tycoon");
                jPanel2.add(jLabelNombreTycoon);

                jLabelSuperadministrador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                jLabelSuperadministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelSuperadministrador.setText("SuperAdministrador");
                jPanel2.add(jLabelSuperadministrador);

                jPanel1.add(jPanel2);

                jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 206, Short.MAX_VALUE));
                jPanel10Layout.setVerticalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 263, Short.MAX_VALUE));

                jPanel3.add(jPanel10);

                jPanel9.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

                jLabelGestionSucursales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelGestionSucursales.setText("Gestion de Sucursales");
                jPanel9.add(jLabelGestionSucursales);

                jButtonCrearNuevaSucursal.setText("Crear nueva sucursal");
                jButtonCrearNuevaSucursal.addActionListener(this::jButtonCrearNuevaSucursalActionPerformed);
                jPanel9.add(jButtonCrearNuevaSucursal);

                jButtonEditarSucursalExistente.setText("Editar sucursal existente");
                jButtonEditarSucursalExistente.addActionListener(this::jButtonEditarSucursalExistenteActionPerformed);
                jPanel9.add(jButtonEditarSucursalExistente);

                jButtonListaSucursales.setText("Lista de sucursales");
                jButtonListaSucursales.addActionListener(this::jButtonListaSucursalesActionPerformed);
                jPanel9.add(jButtonListaSucursales);

                jPanel3.add(jPanel9);

                jPanel11.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

                jLabelGestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelGestionUsuarios.setText("Gestion de Usuarios");
                jPanel11.add(jLabelGestionUsuarios);

                jButtonRegistroUsuario.setText("Registrar nuevo usuario");
                jButtonRegistroUsuario.addActionListener(this::jButtonRegistroUsuarioActionPerformed);
                jPanel11.add(jButtonRegistroUsuario);

                jButtonModificarUsuario.setText("Modificar usuario");
                jButtonModificarUsuario.addActionListener(this::jButtonModificarUsuarioActionPerformed);
                jPanel11.add(jButtonModificarUsuario);

                jButtonAsignarUsurioASucursal.setText("Asignar usuario a sucursal");
                jButtonAsignarUsurioASucursal.addActionListener(this::jButtonAsignarUsurioASucursalActionPerformed);
                jPanel11.add(jButtonAsignarUsurioASucursal);

                jButtonListaUsuarios.setText("Lista de todos los usuarios");
                jButtonListaUsuarios.addActionListener(this::jButtonListaUsuariosActionPerformed);
                jPanel11.add(jButtonListaUsuarios);

                jPanel3.add(jPanel11);

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 206, Short.MAX_VALUE));
                jPanel8Layout.setVerticalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 263, Short.MAX_VALUE));

                jPanel3.add(jPanel8);

                jPanel1.add(jPanel3);

                jPanel12.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 206, Short.MAX_VALUE));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 343, Short.MAX_VALUE));

                jPanel12.add(jPanel13);

                jPanel14.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Consultas y reportes");
                jPanel14.add(jLabel5);

                jButtonEstadisticasGlobales.setText("Ver estadisticas globlales");
                jPanel14.add(jButtonEstadisticasGlobales);

                jButtonRankingJugadores.setText("Ver ranking de jugadores");
                jPanel14.add(jButtonRankingJugadores);

                jPanel12.add(jPanel14);

                jPanel15.setLayout(new java.awt.GridLayout(0, 1));

                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("Configuracion del juego");
                jPanel15.add(jLabel6);

                jButtonParametrosJuego.setText("Parametros del juego");
                jPanel15.add(jButtonParametrosJuego);

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 114, Short.MAX_VALUE));

                jPanel15.add(jPanel6);

                jPanel12.add(jPanel15);

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 206, Short.MAX_VALUE));
                jPanel16Layout.setVerticalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 343, Short.MAX_VALUE));

                jPanel12.add(jPanel16);

                jPanel1.add(jPanel12);

                jPanel17.setLayout(new java.awt.GridLayout(1, 0));

                javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
                jPanel19.setLayout(jPanel19Layout);
                jPanel19Layout.setHorizontalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 294, Short.MAX_VALUE));
                jPanel19Layout.setVerticalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 78, Short.MAX_VALUE));

                jPanel17.add(jPanel19);

                jPanel20.setLayout(new java.awt.GridLayout(0, 1));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 294, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 26, Short.MAX_VALUE));

                jPanel20.add(jPanel4);

                jButtonCerrarSesion.setText("Cerrar sesion");
                jButtonCerrarSesion.addActionListener(this::jButtonCerrarSesionActionPerformed);
                jPanel20.add(jButtonCerrarSesion);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 294, Short.MAX_VALUE));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 26, Short.MAX_VALUE));

                jPanel20.add(jPanel5);

                jPanel17.add(jPanel20);

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 294, Short.MAX_VALUE));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 78, Short.MAX_VALUE));

                jPanel17.add(jPanel18);

                jPanel1.add(jPanel17);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegistroUsuarioActionPerformed
                try {
                        if (haySucursales()) {
                                FrameEditorUsuario frameRegistroUsuario = new FrameEditorUsuario();
                                frameRegistroUsuario.setVisible(true);
                                this.dispose();
                        } else {
                                String mensajeError = "No hay sucursales registradas en el sistema. \n Por favor, registre al menos una sucursal antes de crear un usuario.";
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                        }
                } catch (SQLException e) {
                        String mensajeError = "Error al verificar las sucursales: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }
        }// GEN-LAST:event_jButtonRegistroUsuarioActionPerformed

        private void jButtonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonModificarUsuarioActionPerformed

                try {
                        if (hayMasDeUnUsuario()) {
                                FrameBuscadorUsuario buscadorUsuario = new FrameBuscadorUsuario();
                                buscadorUsuario.setVisible(true);
                        } else {
                                String mensajeError = "No hay suficientes usuarios registrados.";
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                        }
                } catch (SQLException e) {
                        String mensajeError = "Error al verificar los usuarios: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }
        }// GEN-LAST:event_jButtonModificarUsuarioActionPerformed

        private void jButtonAsignarUsurioASucursalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAsignarUsurioASucursalActionPerformed
                try {
                        if (hayMasDeUnUsuario()) {
                                FrameAsignarSucursal frameAsignarSucursal = new FrameAsignarSucursal();
                                frameAsignarSucursal.setVisible(true);
                                this.dispose();
                        } else {
                                String mensajeError = "No hay suficientes usuarios registrados en el sistema para asignar a una sucursal.";
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                        }
                } catch (SQLException e) {
                        String mensajeError = "Error al verificar los usuarios: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }

        }// GEN-LAST:event_jButtonAsignarUsurioASucursalActionPerformed

        private void jButtonListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonListaUsuariosActionPerformed
                FrameListaUsuarios frameListaUsuarios = new FrameListaUsuarios();
                frameListaUsuarios.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButtonListaUsuariosActionPerformed

        private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCerrarSesionActionPerformed
                FrameLogin frameLogin = new FrameLogin();
                frameLogin.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButtonCerrarSesionActionPerformed

        private void jButtonCrearNuevaSucursalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCrearNuevaSucursalActionPerformed
                FrameEditorSucursal frameNuevaSucursal = new FrameEditorSucursal();
                frameNuevaSucursal.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButtonCrearNuevaSucursalActionPerformed

        private void jButtonEditarSucursalExistenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditarSucursalExistenteActionPerforme
                try {
                        if (haySucursales()) {
                                FrameBuscadorSucursal buscadorSucursal = new FrameBuscadorSucursal(this, true, this);
                                buscadorSucursal.setVisible(true);
                        } else {
                                String mensajeError = "No hay sucursales registradas en el sistema.";
                                MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);

                        }
                } catch (SQLException e) {
                        String mensajeError = "Error al verificar las sucursales: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }

        }// GEN-LAST:event_jButtonEditarSucursalExistenteActionPerformed

        private void jButtonListaSucursalesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonListaSucursalesActionPerformed
                FrameListaSucursales framelistaSucursales = new FrameListaSucursales();
                framelistaSucursales.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButtonListaSucursalesActionPerformed

        private boolean hayMasDeUnUsuario() throws SQLException {
                UsuarioDAO usuarioDAO = new UsuarioDAO();
                List<Usuario> usuarios = null;
                try {
                        usuarios = usuarioDAO.obtenerTodo();
                } catch (SQLException ex) {
                        throw new SQLException("Error en hayMasDeUnUsuario: " + ex.getMessage());
                }
                return usuarios.size() > 1;
        }

        private boolean haySucursales() throws SQLException {
                SucursalDAO sucursalDAO = new SucursalDAO();
                List<Sucursal> sucursales = null;
                try {
                        sucursales = sucursalDAO.obtenerTodo();
                } catch (SQLException ex) {
                        throw new SQLException("Error en haySucursales: " + ex.getMessage());
                }
                return !sucursales.isEmpty();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonAsignarUsurioASucursal;
        private javax.swing.JButton jButtonCerrarSesion;
        private javax.swing.JButton jButtonCrearNuevaSucursal;
        private javax.swing.JButton jButtonEditarSucursalExistente;
        private javax.swing.JButton jButtonEstadisticasGlobales;
        private javax.swing.JButton jButtonListaSucursales;
        private javax.swing.JButton jButtonListaUsuarios;
        private javax.swing.JButton jButtonModificarUsuario;
        private javax.swing.JButton jButtonParametrosJuego;
        private javax.swing.JButton jButtonRankingJugadores;
        private javax.swing.JButton jButtonRegistroUsuario;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabelGestionSucursales;
        private javax.swing.JLabel jLabelGestionUsuarios;
        private javax.swing.JLabel jLabelNombreTycoon;
        private javax.swing.JLabel jLabelSuperadministrador;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel19;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel20;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        // End of variables declaration//GEN-END:variables
}
