/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.superadmin;

/**
 *
 * @author Matul
 */
public class PanelEstadisticaSucursal extends javax.swing.JPanel {

    private int nivelMax;
    private int partidasJugadas;
    private int pedidosEntregados;
    private int pedidosCancelados;
    private int pedidosNoEntregados;
    private String nombreSucursal;

    /**
     * Creates new form PanelEstadisticaSucursal
     */
    public PanelEstadisticaSucursal(int nivelMax, int partidasJugadas, int pedidosEntregados, int pedidosCancelados,
            int pedidosNoEntregados,
            String nombreSucursal) {
        initComponents();
        this.nivelMax = nivelMax;
        this.partidasJugadas = partidasJugadas;
        this.pedidosEntregados = pedidosEntregados;
        this.pedidosCancelados = pedidosCancelados;
        this.pedidosNoEntregados = pedidosNoEntregados;
        this.nombreSucursal = nombreSucursal;
        cargarDatos();
    }

    String getNombreSucursal() {
        return nombreSucursal;
    }

    private void cargarDatos() {
        jLabelNivelMaximo.setText(String.valueOf(nivelMax));
        jLabelPartidasJugadas.setText(String.valueOf(partidasJugadas));
        jLabelPedidosNoEntregados.setText(String.valueOf(pedidosNoEntregados));
        jLabelPedidosCancelados.setText(String.valueOf(pedidosCancelados));
        jLabelPedidosEntregados.setText(String.valueOf(pedidosEntregados));
        jLabelNombreSucursal.setText("Nombre sucursal: " + nombreSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelNombreSucursal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelTitlePartidas = new javax.swing.JLabel();
        jLabelNivelMaxTitle = new javax.swing.JLabel();
        jLabelPuntajeAcumuladoTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPartidasJugadas = new javax.swing.JLabel();
        jLabelNivelMaximo = new javax.swing.JLabel();
        jLabelPedidosEntregados = new javax.swing.JLabel();
        jLabelPedidosCancelados = new javax.swing.JLabel();
        jLabelPedidosNoEntregados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelNombreSucursal.setText("Nombre sucursal: xxxxxxx");
        jPanel5.add(jLabelNombreSucursal);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelTitlePartidas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitlePartidas.setText("Total partidas Jugadas");
        jPanel7.add(jLabelTitlePartidas);

        jLabelNivelMaxTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNivelMaxTitle.setText("Nivel Maximo Alcanzado");
        jPanel7.add(jLabelNivelMaxTitle);

        jLabelPuntajeAcumuladoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPuntajeAcumuladoTitle.setText("Pedidos Entregados");
        jPanel7.add(jLabelPuntajeAcumuladoTitle);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pedidos Cancelados");
        jPanel7.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Pedidos No Entregados");
        jPanel7.add(jLabel2);
        jPanel7.add(jLabel3);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelPartidasJugadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartidasJugadas.setText("00");
        jPanel8.add(jLabelPartidasJugadas);

        jLabelNivelMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivelMaximo.setText("00");
        jPanel8.add(jLabelNivelMaximo);

        jLabelPedidosEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosEntregados.setText("00");
        jPanel8.add(jLabelPedidosEntregados);

        jLabelPedidosCancelados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosCancelados.setText("00");
        jPanel8.add(jLabelPedidosCancelados);

        jLabelPedidosNoEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosNoEntregados.setText("00");
        jPanel8.add(jLabelPedidosNoEntregados);
        jPanel8.add(jLabel4);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNivelMaxTitle;
    private javax.swing.JLabel jLabelNivelMaximo;
    private javax.swing.JLabel jLabelNombreSucursal;
    private javax.swing.JLabel jLabelPartidasJugadas;
    private javax.swing.JLabel jLabelPedidosCancelados;
    private javax.swing.JLabel jLabelPedidosEntregados;
    private javax.swing.JLabel jLabelPedidosNoEntregados;
    private javax.swing.JLabel jLabelPuntajeAcumuladoTitle;
    private javax.swing.JLabel jLabelTitlePartidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
