/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import com.mycompany.primera_practica_codigo.modelo.entidades.Partida;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;

/**
 *
 * @author Matul
 */
public class FrameFinalPartida extends javax.swing.JFrame {

    private Partida partida;
    private Usuario usuario;

    /**
     * Creates new form FrameFinalPartida
     */
    public FrameFinalPartida(Partida partida) {
        initComponents();
        setLocationRelativeTo(null);
        this.partida = partida;
        this.usuario = partida.getJugador();
        llenarDatos();
    }

    private void llenarDatos() {
        jLabelPuntaje.setText(String.valueOf(partida.getPuntajeTotal()));
        jLabelNivelAlcanzado.setText(String.valueOf(partida.getNivel()));
        jLabelPedidosEntregados.setText(String.valueOf(partida.getPedidosCompletados()));
        jLabelPedidosCancelados.setText(String.valueOf(partida.getPedidosCancelados()));
        jLabelPedidosNoEntregados.setText(String.valueOf(partida.getPedidosNoEntregados()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelTitlePuntajeTotal = new javax.swing.JLabel();
        jLabelNivelAlcanzadoTitle = new javax.swing.JLabel();
        jLabelPedidosCompletadosTitle = new javax.swing.JLabel();
        jLabelMaxPedidosCanceladosTitle = new javax.swing.JLabel();
        jLabelPedidosNoEntregadosTitle = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPuntaje = new javax.swing.JLabel();
        jLabelNivelAlcanzado = new javax.swing.JLabel();
        jLabelPedidosEntregados = new javax.swing.JLabel();
        jLabelPedidosCancelados = new javax.swing.JLabel();
        jLabelPedidosNoEntregados = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setText("La partida a finalizado");
        jPanel5.add(jLabelTitle);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelTitlePuntajeTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitlePuntajeTotal.setText("Puntaje Total Obtenido");
        jPanel7.add(jLabelTitlePuntajeTotal);

        jLabelNivelAlcanzadoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNivelAlcanzadoTitle.setText("Nivel alcanzado");
        jPanel7.add(jLabelNivelAlcanzadoTitle);

        jLabelPedidosCompletadosTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPedidosCompletadosTitle.setText("Pedidos completados correctamente");
        jPanel7.add(jLabelPedidosCompletadosTitle);

        jLabelMaxPedidosCanceladosTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMaxPedidosCanceladosTitle.setText("Pedidos cancelados");
        jPanel7.add(jLabelMaxPedidosCanceladosTitle);

        jLabelPedidosNoEntregadosTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPedidosNoEntregadosTitle.setText("Pedidos no entregados a tiempo");
        jPanel7.add(jLabelPedidosNoEntregadosTitle);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntaje.setText("00");
        jPanel8.add(jLabelPuntaje);

        jLabelNivelAlcanzado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivelAlcanzado.setText("00");
        jPanel8.add(jLabelNivelAlcanzado);

        jLabelPedidosEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosEntregados.setText("00");
        jPanel8.add(jLabelPedidosEntregados);

        jLabelPedidosCancelados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosCancelados.setText("00");
        jPanel8.add(jLabelPedidosCancelados);

        jLabelPedidosNoEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidosNoEntregados.setText("00");
        jPanel8.add(jLabelPedidosNoEntregados);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jPanel4.add(jLabel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jPanel10.add(jLabel12);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonRegresar);
        jPanel10.add(jLabel11);

        jPanel4.add(jPanel10);
        jPanel4.add(jLabel10);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
        FrameInicioJugador frameInicioJugador = new FrameInicioJugador(usuario);
        frameInicioJugador.setVisible(true);
    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaxPedidosCanceladosTitle;
    private javax.swing.JLabel jLabelNivelAlcanzado;
    private javax.swing.JLabel jLabelNivelAlcanzadoTitle;
    private javax.swing.JLabel jLabelPedidosCancelados;
    private javax.swing.JLabel jLabelPedidosCompletadosTitle;
    private javax.swing.JLabel jLabelPedidosEntregados;
    private javax.swing.JLabel jLabelPedidosNoEntregados;
    private javax.swing.JLabel jLabelPedidosNoEntregadosTitle;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitlePuntajeTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
