/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import java.sql.SQLException;
import java.util.List;
import com.mycompany.primera_practica_codigo.modelo.dao.PartidaDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Partida;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;

/**
 *
 * @author Matul
 */
public class FrameHistorialDePartidasJugador extends javax.swing.JFrame {

    List<Partida> partidas;
    private int idJugador;
    private Usuario usuario;

    /**
     * Creates new form FrameHistorialDePartidasJugador
     */
    public FrameHistorialDePartidasJugador(Usuario usuario) {
        this.usuario = usuario;
        this.idJugador = this.usuario.getIdUsuario();
        initComponents();
        setLocationRelativeTo(null);
        recuperarPartidas();
        cargarPartidas();
    }

    private void cargarPartidas() {

        if (this.partidas == null || this.partidas.isEmpty()) {
            String mensajeError = "No se encontraron partidas para este jugador.";
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
            return;
        }

        // limpiar tabla antes de cargar datos
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "Puntaje Total", "Pedidos Entregados", "Pedidos Cancelados", "Pedidos No Entregados",
                        "Total pedidos Generados", "Nivel", "Fecha y Hora Fin" }));

        for (Partida partida : this.partidas) {
            Object[] fila = new Object[7];
            fila[0] = partida.getPuntajeTotal();
            fila[1] = partida.getPedidosCompletados();
            fila[2] = partida.getPedidosCancelados();
            fila[3] = partida.getPedidosNoEntregados();
            fila[4] = partida.getContadorPedidos();
            fila[5] = partida.getNivel();
            fila[6] = partida.getFechaYHoraFin();

            ((javax.swing.table.DefaultTableModel) jTableDatos.getModel()).addRow(fila);
        }
    }

    private void recuperarPartidas() {
        PartidaDAO partidaDAO = new PartidaDAO();
        try {
            partidas = partidaDAO.obtenerPartidasPorUsuario(idJugador);
        } catch (SQLException e) {
            String mensajeError = "Error al recuperar las partidas: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setText("Historial de Partidas");
        jPanel5.add(jLabelTitle);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableDatos);

        jPanel7.add(jScrollPane1);

        jPanel3.add(jPanel7);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 10, 20));
        jPanel10.add(jLabel12);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonRegresar);
        jPanel10.add(jLabel11);

        jPanel4.add(jPanel10);
        jPanel4.add(jLabel10);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        FrameInicioJugador frameInicioJugador = new FrameInicioJugador(usuario);
        frameInicioJugador.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    // End of variables declaration//GEN-END:variables
}
