/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import java.sql.SQLException;

import com.mycompany.primera_practica_codigo.modelo.dao.JugadorDAO;
import com.mycompany.primera_practica_codigo.modelo.dao.ProductoDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Jugador;
import com.mycompany.primera_practica_codigo.modelo.entidades.Partida;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.FrameLogin;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;

/**
 *
 * @author Matul
 */
public class FrameInicioJugador extends javax.swing.JFrame {

    private Usuario usuario;
    private Jugador jugador;

    /**
     * Creates new form FrameInicioJugador
     * 
     * @param usuario
     */
    public FrameInicioJugador(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        cargarJugador();
    }

    private void cargarJugador() {
        JugadorDAO jugadorDAO = new JugadorDAO();
        try {
            this.jugador = jugadorDAO.encontrarPorID(usuario.getIdUsuario()).orElse(null);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los datos del jugador: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonIniciarPartida = new javax.swing.JButton();
        jButtonMisEstadisticas = new javax.swing.JButton();
        jButtonHistorialDePartidas = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabelTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTitle.setText("Pizza Express Tycoon");
        jPanel2.add(jLabelTitle);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 132, Short.MAX_VALUE));

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

        jButtonIniciarPartida.setText("Iniciar Partida");
        jButtonIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarPartidaActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonIniciarPartida);

        jButtonMisEstadisticas.setText("Mis estadisticas");
        jButtonMisEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisEstadisticasActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonMisEstadisticas);

        jButtonHistorialDePartidas.setText("Historial de Partidas");
        jButtonHistorialDePartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialDePartidasActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonHistorialDePartidas);

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 132, Short.MAX_VALUE));

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel19Layout.setVerticalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 78, Short.MAX_VALUE));

        jPanel17.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 26, Short.MAX_VALUE));

        jPanel20.add(jPanel7);

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        jPanel20.add(jButtonCerrarSesion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 26, Short.MAX_VALUE));

        jPanel20.add(jPanel8);

        jPanel17.add(jPanel20);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE));
        jPanel18Layout.setVerticalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 78, Short.MAX_VALUE));

        jPanel17.add(jPanel18);

        jPanel1.add(jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHistorialDePartidasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonHistorialDePartidasActionPerformed
        FrameHistorialDePartidasJugador frameHistorialDePartidasJugador = new FrameHistorialDePartidasJugador(usuario);
        frameHistorialDePartidasJugador.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonHistorialDePartidasActionPerformed

    private void jButtonIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonIniciarPartidaActionPerformed
        if (!hayProductosActivosParaInciarPartida()) {
            String mensajeError = "No hay productos activos para iniciar una nueva partida.";
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
            return;
        }
        Partida partida = new Partida(usuario);
        partida.iniciarPartida();
        this.dispose();
    }// GEN-LAST:event_jButtonIniciarPartidaActionPerformed

    private boolean hayProductosActivosParaInciarPartida() {
        ProductoDAO productoDAO = new ProductoDAO();
        try {
            return productoDAO.hayProductosActivosEnSucursal(usuario.getSucursal().getId());
        } catch (SQLException e) {
            String mensajeError = "Error al verificar productos activos: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
            return false;
        }
    }

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        this.dispose();
        FrameLogin frameLogin = new FrameLogin();
        frameLogin.setVisible(true);
    }// GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonMisEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMisEstadisticasActionPerformed
        FrameMisEstadisticas frameMisEstadisticas = new FrameMisEstadisticas(jugador, usuario);
        frameMisEstadisticas.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonMisEstadisticasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonHistorialDePartidas;
    private javax.swing.JButton jButtonIniciarPartida;
    private javax.swing.JButton jButtonMisEstadisticas;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
