/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.util.Temporizable;
import com.mycompany.primera_practica_codigo.util.Temporizador;

/**
 *
 * @author Matul
 */
public class FrameJuego extends javax.swing.JFrame implements Temporizable {

    private Temporizador temporizador;
    private Usuario usuario;

    /**
     * Creates new form FrameJuego
     */
    public FrameJuego(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        temporizador = new Temporizador();
        temporizador.setTemporizable(this);
        temporizador.start();
        this.usuario = usuario;
        colocarDatosUsuario();
    }

    @Override
    public void cambioDeTiempo(int segundos, int minutos) {
        String tiempoFormateado = String.format("%02d : %02d", minutos, segundos);
        jLabelTiempo.setText(tiempoFormateado);
    }

    private void colocarDatosUsuario() {
        jLabelNombreJugador.setText(usuario.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDatos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelJugador = new javax.swing.JLabel();
        jLabelNombreJugador = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jLabelNivelSiguiente = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPuntajeTitle = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelTiempoTitle = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        jPanelEspacio = new javax.swing.JPanel();
        jPanelPedidos = new javax.swing.JPanel();
        jPanelOpcionesSalida = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanelDatos.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        jLabelJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJugador.setText("Jugador");
        jPanel6.add(jLabelJugador);

        jLabelNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreJugador.setText("Nombre Jugador");
        jPanel6.add(jLabelNombreJugador);

        jPanelDatos.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNivel.setText("Nivel : 1");
        jPanel7.add(jLabelNivel);

        jLabelNivelSiguiente.setText("Siguiente 10 / 100 EXP");
        jPanel7.add(jLabelNivelSiguiente);

        jPanelDatos.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        jLabelPuntajeTitle.setText("Puntaje");
        jPanel8.add(jLabelPuntajeTitle);

        jLabelPuntaje.setText("1253 puntos");
        jPanel8.add(jLabelPuntaje);

        jPanelDatos.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(0, 1));

        jLabelTiempoTitle.setText("Tiempo restante de turno");
        jPanel9.add(jLabelTiempoTitle);

        jLabelTiempo.setText("03 : 04 ");
        jPanel9.add(jLabelTiempo);

        jPanelDatos.add(jPanel9);

        jPanel1.add(jPanelDatos);

        javax.swing.GroupLayout jPanelEspacioLayout = new javax.swing.GroupLayout(jPanelEspacio);
        jPanelEspacio.setLayout(jPanelEspacioLayout);
        jPanelEspacioLayout.setHorizontalGroup(
                jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 908, Short.MAX_VALUE));
        jPanelEspacioLayout.setVerticalGroup(
                jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 120, Short.MAX_VALUE));

        jPanel1.add(jPanelEspacio);

        javax.swing.GroupLayout jPanelPedidosLayout = new javax.swing.GroupLayout(jPanelPedidos);
        jPanelPedidos.setLayout(jPanelPedidosLayout);
        jPanelPedidosLayout.setHorizontalGroup(
                jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 908, Short.MAX_VALUE));
        jPanelPedidosLayout.setVerticalGroup(
                jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 120, Short.MAX_VALUE));

        jPanel1.add(jPanelPedidos);

        javax.swing.GroupLayout jPanelOpcionesSalidaLayout = new javax.swing.GroupLayout(jPanelOpcionesSalida);
        jPanelOpcionesSalida.setLayout(jPanelOpcionesSalidaLayout);
        jPanelOpcionesSalidaLayout.setHorizontalGroup(
                jPanelOpcionesSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 908, Short.MAX_VALUE));
        jPanelOpcionesSalidaLayout.setVerticalGroup(
                jPanelOpcionesSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 120, Short.MAX_VALUE));

        jPanel1.add(jPanelOpcionesSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNivelSiguiente;
    private javax.swing.JLabel jLabelNombreJugador;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelPuntajeTitle;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelTiempoTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelEspacio;
    private javax.swing.JPanel jPanelOpcionesSalida;
    private javax.swing.JPanel jPanelPedidos;
    // End of variables declaration//GEN-END:variables

}
