/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import com.mycompany.primera_practica_codigo.modelo.entidades.Jugador;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;

/**
 *
 * @author Matul
 */
public class FrameMisEstadisticas extends javax.swing.JFrame {

    private Jugador jugador;
    private Usuario usuario;

    /**
     * Creates new form FrameMisEstadisticas
     */
    public FrameMisEstadisticas(Jugador jugador, Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        this.jugador = jugador;
        cargarEstadisticas();
    }

    private void cargarEstadisticas() {
        jLabelPartidasJugadas.setText(String.valueOf(jugador.getPartidasJugadas()));
        jLabelNivelMaximo.setText(String.valueOf(jugador.getNivelMaximoAlcanzado()));
        jLabelPuntajeMaximo.setText(String.valueOf(jugador.getPuntajeMaximo()));
        jLabelPuntajeAcumulado.setText(String.valueOf(jugador.getPuntajeTotalAcumulado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelTitlePartidas = new javax.swing.JLabel();
        jLabelNivelMaxTitle = new javax.swing.JLabel();
        jLabelPuntajeMaximoTitle = new javax.swing.JLabel();
        jLabelPuntajeAcumuladoTitle = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPartidasJugadas = new javax.swing.JLabel();
        jLabelNivelMaximo = new javax.swing.JLabel();
        jLabelPuntajeMaximo = new javax.swing.JLabel();
        jLabelPuntajeAcumulado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setText("Mis Estadisticas ");
        jPanel5.add(jLabelTitle);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelTitlePartidas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitlePartidas.setText("Partidas Jugadas");
        jPanel7.add(jLabelTitlePartidas);

        jLabelNivelMaxTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNivelMaxTitle.setText("Nivel Maximo Alcanzado");
        jPanel7.add(jLabelNivelMaxTitle);

        jLabelPuntajeMaximoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPuntajeMaximoTitle.setText("Puntaje Maximo ");
        jPanel7.add(jLabelPuntajeMaximoTitle);

        jLabelPuntajeAcumuladoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPuntajeAcumuladoTitle.setText("Puntaje Acumulado");
        jPanel7.add(jLabelPuntajeAcumuladoTitle);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelPartidasJugadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartidasJugadas.setText("00");
        jPanel8.add(jLabelPartidasJugadas);

        jLabelNivelMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivelMaximo.setText("00");
        jPanel8.add(jLabelNivelMaximo);

        jLabelPuntajeMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntajeMaximo.setText("00");
        jPanel8.add(jLabelPuntajeMaximo);

        jLabelPuntajeAcumulado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntajeAcumulado.setText("00");
        jPanel8.add(jLabelPuntajeAcumulado);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jPanel4.add(jLabel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jPanel10.add(jLabel12);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonRegresar);
        jPanel10.add(jLabel11);

        jPanel4.add(jPanel10);
        jPanel4.add(jLabel10);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        FrameInicioJugador frameInicioJugador = new FrameInicioJugador(usuario);
        frameInicioJugador.setVisible(true);
        this.dispose();

    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNivelMaxTitle;
    private javax.swing.JLabel jLabelNivelMaximo;
    private javax.swing.JLabel jLabelPartidasJugadas;
    private javax.swing.JLabel jLabelPuntajeAcumulado;
    private javax.swing.JLabel jLabelPuntajeAcumuladoTitle;
    private javax.swing.JLabel jLabelPuntajeMaximo;
    private javax.swing.JLabel jLabelPuntajeMaximoTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitlePartidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
