/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.juego;

import com.mycompany.primera_practica_codigo.modelo.entidades.EstadoPedido;
import com.mycompany.primera_practica_codigo.modelo.entidades.Pedido;
import com.mycompany.primera_practica_codigo.util.Actualizable;
import com.mycompany.primera_practica_codigo.util.ActualizablePedido;
import com.mycompany.primera_practica_codigo.util.Temporizable;
import com.mycompany.primera_practica_codigo.util.Temporizador;

/**
 *
 * @author Matul
 */
public class JPanelPedido extends javax.swing.JPanel implements Temporizable, ActualizablePedido {

    private Pedido pedido;
    private int tiempoLimiteSeg;
    private int timpoRestanteSMinutos;
    private int tiempoRestanteSSegundos;
    private String estadoActual;
    private String nombreProducto;
    private int numeroOrden;
    private Temporizador temporizador;

    /**
     * Creates new form JPanelPedido
     */
    public JPanelPedido(Pedido pedido) {
        this.pedido = pedido;
        this.pedido.setActualizablePedido(this);
        this.tiempoLimiteSeg = pedido.getTiempoLimiteSeg();
        this.timpoRestanteSMinutos = pedido.getTiempoLimiteSeg() / 60;
        this.tiempoRestanteSSegundos = pedido.getTiempoLimiteSeg() % 60;
        initComponents();
        colocarDatosIniciales();
        activarTemporizador();
    }

    public int getNumeroOrden() {
        return numeroOrden;
    }

    public void detenerTemporizador() {
        if (temporizador != null && temporizador.isAlive()) {
            temporizador.interrupt();
            temporizador = null;
        }
    }

    private void activarTemporizador() {
        this.temporizador = new Temporizador(timpoRestanteSMinutos, tiempoRestanteSSegundos);
        this.temporizador.setTemporizable(this);
        this.temporizador.start();
    }

    private void colocarDatosIniciales() {
        this.numeroOrden = pedido.getNumeroPedido();
        this.nombreProducto = pedido.getNombreProducto();
        this.estadoActual = pedido.getEstadoActual().toString();
        jLabelNumeroOrden.setText("Número de Orden: #" + numeroOrden);
        jLabelNombreProducto.setText(nombreProducto);
        jLabelEstadoActual.setText("Estado Actual: " + estadoActual);
    }

    @Override
    public void cambioDeTiempo(int tiempoRestanteSeg, int minutos) {
        this.timpoRestanteSMinutos = minutos;
        this.tiempoRestanteSSegundos = tiempoRestanteSeg % 60;
        jLabelTiempoRestante.setText(String.format("%02d : %02d", timpoRestanteSMinutos, tiempoRestanteSSegundos));
        int tiempoTotalRestante = (minutos * 60) + tiempoRestanteSeg;
        jProgressBarTiempo.setValue((int) (((double) tiempoTotalRestante / tiempoLimiteSeg) * 100));
        pedido.restarTiempo();
    }

    @Override
    public void actualizarEstadoPedido(EstadoPedido nuevoEstado) {

        if (nuevoEstado == EstadoPedido.RECIBIDA) {
            jLabelEstadoActual.setText("Estado Actual: RECIBIDA");
        } else if (nuevoEstado == EstadoPedido.PREPARANDO) {
            jLabelEstadoActual.setText("Estado Actual: PREPARANDO");
        } else if (nuevoEstado == EstadoPedido.EN_HORNO) {
            jLabelEstadoActual.setText("Estado Actual: EN HORNO");
        } else if (nuevoEstado == EstadoPedido.ENTREGADO) {
            jLabelEstadoActual.setText("Estado Actual: ENTREGADO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNumeroOrden = new javax.swing.JLabel();
        jPanelNombreYTIempo = new javax.swing.JPanel();
        jLabelNombreProducto = new javax.swing.JLabel();
        jPanelTiempo = new javax.swing.JPanel();
        jLabelTiempoTitle = new javax.swing.JLabel();
        jProgressBarTiempo = new javax.swing.JProgressBar();
        jLabelTiempoRestante = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEstadoActual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonSiguientePaso = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabelNumeroOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroOrden.setText("Numero de Orden: #");
        jPanel1.add(jLabelNumeroOrden);

        add(jPanel1);

        jPanelNombreYTIempo.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLabelNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreProducto.setText("Nombre producto");
        jPanelNombreYTIempo.add(jLabelNombreProducto);

        jPanelTiempo.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabelTiempoTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTiempoTitle.setText("Tiempo");
        jPanelTiempo.add(jLabelTiempoTitle);
        jPanelTiempo.add(jProgressBarTiempo);

        jLabelTiempoRestante.setText("00 : 00");
        jPanelTiempo.add(jLabelTiempoRestante);

        jPanelNombreYTIempo.add(jPanelTiempo);

        add(jPanelNombreYTIempo);

        jPanel2.setLayout(new java.awt.GridLayout());

        jLabelEstadoActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstadoActual.setText("Estado Actual");
        jPanel2.add(jLabelEstadoActual);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jPanel3.add(jLabel5);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jButtonSiguientePaso.setText("Siguiente Paso");
        jButtonSiguientePaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguientePasoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSiguientePaso);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonCancelar);

        jPanel3.add(jPanel4);
        jPanel3.add(jLabel7);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguientePasoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSiguientePasoActionPerformed
        this.pedido.avanzarEstado();
    }// GEN-LAST:event_jButtonSiguientePasoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelarActionPerformed
        this.pedido.cancelar();
    }// GEN-LAST:event_jButtonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSiguientePaso;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEstadoActual;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelNumeroOrden;
    private javax.swing.JLabel jLabelTiempoRestante;
    private javax.swing.JLabel jLabelTiempoTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelNombreYTIempo;
    private javax.swing.JPanel jPanelTiempo;
    private javax.swing.JProgressBar jProgressBarTiempo;
    // End of variables declaration//GEN-END:variables
}
