/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JFrame;

import com.mycompany.primera_practica_codigo.modelo.dao.ProductoDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Producto;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;

/**
 *
 * @author Matul
 */
public class FrameBuscadorProducto extends javax.swing.JDialog {

        private Usuario usuario;
        private List<Producto> productos;
        private JFrame frameAnterior;

        /**
         * Creates new form FrameBuscadorProducto
         */
        public FrameBuscadorProducto(java.awt.Frame parent, JFrame frameAnterior, boolean modal, Usuario usuario) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
                setTitle("Buscador de Productos");
                this.usuario = usuario;
                this.frameAnterior = frameAnterior;
                cargarProductos();
        }

        private void cargarProductos() {
                int idSucursal = usuario.getSucursal().getId(); // Obtener el ID de la sucursal del usuario
                Producto producto = new Producto();
                ProductoDAO productoDAO = new ProductoDAO();
                productos = null;
                try {
                        productos = productoDAO.obtenerTodoPorSucursal(idSucursal);
                } catch (SQLException e) {
                        String mensajeError = "Error al cargar los productos: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
                }
                jComboBoxProductos.removeAllItems();
                for (Producto p : productos) {
                        jComboBoxProductos.addItem(p.getNombre());
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabelTitle = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jPanel9 = new javax.swing.JPanel();
                jComboBoxProductos = new javax.swing.JComboBox<>();
                jButtonEditar = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jPanel17 = new javax.swing.JPanel();
                jPanel19 = new javax.swing.JPanel();
                jPanel20 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jButtonRegresar = new javax.swing.JButton();
                jPanel8 = new javax.swing.JPanel();
                jPanel18 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

                jLabelTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelTitle.setText("Seleccione el producto que desea editar");
                jPanel2.add(jLabelTitle);

                jPanel1.add(jPanel2);

                jPanel3.setLayout(new java.awt.GridLayout());

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 82, Short.MAX_VALUE));

                jPanel3.add(jPanel4);

                jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

                jPanel9.setLayout(new java.awt.GridLayout(0, 1));

                jComboBoxProductos.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jPanel9.add(jComboBoxProductos);

                jPanel5.add(jPanel9);

                jButtonEditar.setText("Editar");
                jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonEditarActionPerformed(evt);
                        }
                });
                jPanel5.add(jButtonEditar);

                jPanel3.add(jPanel5);

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 82, Short.MAX_VALUE));

                jPanel3.add(jPanel6);

                jPanel1.add(jPanel3);

                jPanel17.setLayout(new java.awt.GridLayout());

                javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
                jPanel19.setLayout(jPanel19Layout);
                jPanel19Layout.setHorizontalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel19Layout.setVerticalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanel17.add(jPanel19);

                jPanel20.setLayout(new java.awt.GridLayout(0, 1));

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 24, Short.MAX_VALUE));

                jPanel20.add(jPanel7);

                jButtonRegresar.setText("Regresar");
                jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRegresarActionPerformed(evt);
                        }
                });
                jPanel20.add(jButtonRegresar);

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel8Layout.setVerticalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 24, Short.MAX_VALUE));

                jPanel20.add(jPanel8);

                jPanel17.add(jPanel20);

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 133, Short.MAX_VALUE));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanel17.add(jPanel18);

                jPanel1.add(jPanel17);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditarActionPerformed
                Producto producto = null;
                String nombreProductoSeleccionado = (String) jComboBoxProductos.getSelectedItem();
                for (Producto p : productos) {
                        if (p.getNombre().equals(nombreProductoSeleccionado)) {
                                producto = p;
                        }
                }

                this.dispose();
                frameAnterior.dispose();
                FrameEditorProducto frameEditorProducto = new FrameEditorProducto(producto, usuario);
                frameEditorProducto.setVisible(true);

        }// GEN-LAST:event_jButtonEditarActionPerformed

        private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
                dispose();
        }// GEN-LAST:event_jButtonRegresarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonEditar;
        private javax.swing.JButton jButtonRegresar;
        private javax.swing.JComboBox<String> jComboBoxProductos;
        private javax.swing.JLabel jLabelTitle;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel19;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel20;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        // End of variables declaration//GEN-END:variables
}
