/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos;

import java.sql.SQLException;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.mycompany.primera_practica_codigo.modelo.dao.ProductoDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Producto;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.FrameInicioAdministradorSucursal;

/**
 *
 * @author Matul
 */
public class FrameListaDeProductos extends javax.swing.JFrame {

        private Usuario usuario;
        private List<Producto> productos;

        /**
         * Creates new form FrameListaDeProductos
         */
        public FrameListaDeProductos(Usuario usuario) {
                initComponents();
                setLocationRelativeTo(null);
                this.usuario = usuario;
                cargarProductos();
        }

        private void cargarProductos() {
                ProductoDAO productoDAO = new ProductoDAO();
                try {
                        productos = productoDAO.obtenerTodoPorSucursal(usuario.getSucursal().getId());
                } catch (SQLException e) {
                        String mensaje = "Error al cargar los productos: " + e.getMessage();
                        MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
                }

                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                modelo.setRowCount(0);

                if (productos == null || productos.isEmpty()) {
                        jPanelListaProductos.removeAll();
                        javax.swing.JLabel mensaje = new javax.swing.JLabel("No hay productos registrados.");
                        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jPanelListaProductos.setLayout(new java.awt.BorderLayout());
                        jPanelListaProductos.add(mensaje, java.awt.BorderLayout.CENTER);
                        jPanelListaProductos.revalidate();
                        jPanelListaProductos.repaint();
                } else {
                        for (Producto producto : productos) {
                                modelo.addRow(new Object[] {
                                                producto.getId(),
                                                producto.getNombre(),
                                                producto.isActivo() ? "Activo" : "Inactivo"
                                });
                        }
                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanelTitle = new javax.swing.JPanel();
                jLabelTitle = new javax.swing.JLabel();
                jPanelListaProductos = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanelRegresar = new javax.swing.JPanel();
                jPanel19 = new javax.swing.JPanel();
                jPanel20 = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jButtonRegresar = new javax.swing.JButton();
                jPanel12 = new javax.swing.JPanel();
                jPanel18 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

                jLabelTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabelTitle.setText("Lista De Productos");
                jPanelTitle.add(jLabelTitle);

                jPanel1.add(jPanelTitle);

                jPanelListaProductos.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null }
                                },
                                new String[] {
                                                "#", "Nombre", "Estado"
                                }));
                jScrollPane1.setViewportView(jTable1);

                jPanelListaProductos.add(jScrollPane1);

                jPanel1.add(jPanelListaProductos);

                jPanelRegresar.setLayout(new java.awt.GridLayout(1, 0));

                javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
                jPanel19.setLayout(jPanel19Layout);
                jPanel19Layout.setHorizontalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 220, Short.MAX_VALUE));
                jPanel19Layout.setVerticalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanelRegresar.add(jPanel19);

                jPanel20.setLayout(new java.awt.GridLayout(0, 1));

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 220, Short.MAX_VALUE));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 24, Short.MAX_VALUE));

                jPanel20.add(jPanel13);

                jButtonRegresar.setText("Regresar");
                jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRegresarActionPerformed(evt);
                        }
                });
                jPanel20.add(jButtonRegresar);

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 220, Short.MAX_VALUE));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 24, Short.MAX_VALUE));

                jPanel20.add(jPanel12);

                jPanelRegresar.add(jPanel20);

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 220, Short.MAX_VALUE));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 72, Short.MAX_VALUE));

                jPanelRegresar.add(jPanel18);

                jPanel1.add(jPanelRegresar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                662,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 166,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
                this.dispose();
                FrameInicioAdministradorSucursal frameInicioAdministradorSucursal = new FrameInicioAdministradorSucursal(
                                usuario);
                frameInicioAdministradorSucursal.setVisible(true);
        }// GEN-LAST:event_jButtonRegresarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonRegresar;
        private javax.swing.JLabel jLabelTitle;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel19;
        private javax.swing.JPanel jPanel20;
        private javax.swing.JPanel jPanelListaProductos;
        private javax.swing.JPanel jPanelRegresar;
        private javax.swing.JPanel jPanelTitle;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables
}
