/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos;

import java.sql.SQLException;
import java.util.List;

import com.mycompany.primera_practica_codigo.modelo.dao.ProductoDAO;
import com.mycompany.primera_practica_codigo.modelo.entidades.Producto;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.MensajeErrorFrame;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.FrameInicioAdministradorSucursal;
import com.mysql.cj.x.protobuf.MysqlxNotice.Frame;

/**
 *
 * @author Matul
 */
public class FrameActivarDesactivarProducto extends javax.swing.JFrame {

    List<Producto> productos;
    Usuario usuario;

    /**
     * Creates new form FrameActivarDesactivarProducto
     */
    public FrameActivarDesactivarProducto(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        cargarProductos();
        cargarEstados();
    }

    private void cargarProductos() {
        int idSucursal = usuario.getSucursal().getId(); // Obtener el ID de la sucursal del usuario
        ProductoDAO productoDAO = new ProductoDAO();
        productos = null;
        try {
            productos = productoDAO.obtenerTodoPorSucursal(idSucursal);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los productos: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
        }
        jComboBoxProductos.removeAllItems();
        for (Producto p : productos) {
            jComboBoxProductos.addItem(p.getNombre());
        }
    }

    private void cargarEstados() {
        jComboBoxActivarDesactivar.removeAllItems();
        jComboBoxActivarDesactivar.addItem("Activar");
        jComboBoxActivarDesactivar.addItem("Desactivar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jComboBoxProductos = new javax.swing.JComboBox<>();
        jLabelEstadoActual = new javax.swing.JLabel();
        jComboBoxActivarDesactivar = new javax.swing.JComboBox<>();
        jButtonAplicar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonRegresar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabelTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTitle.setText("Activar / Desactivar  Producto");
        jPanel2.add(jLabelTitle);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 216, Short.MAX_VALUE));

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

        jPanel9.setLayout(new java.awt.GridLayout(0, 1));

        jComboBoxProductos.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductosActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxProductos);

        jPanel5.add(jPanel9);

        jLabelEstadoActual.setText("Estado actual  : ");
        jPanel5.add(jLabelEstadoActual);

        jComboBoxActivarDesactivar.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBoxActivarDesactivar);

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAplicar);

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 216, Short.MAX_VALUE));

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel19Layout.setVerticalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 72, Short.MAX_VALUE));

        jPanel17.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 24, Short.MAX_VALUE));

        jPanel20.add(jPanel7);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel20.add(jButtonRegresar);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 24, Short.MAX_VALUE));

        jPanel20.add(jPanel8);

        jPanel17.add(jPanel20);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 133, Short.MAX_VALUE));
        jPanel18Layout.setVerticalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 72, Short.MAX_VALUE));

        jPanel17.add(jPanel18);

        jPanel1.add(jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProductosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxProductosActionPerformed
        actualizarEstadoActual();
    }// GEN-LAST:event_jComboBoxProductosActionPerformed

    private void actualizarEstadoActual() {
        String nombreProductoSeleccionado = (String) jComboBoxProductos.getSelectedItem();
        for (Producto producto : productos) {
            if (producto.getNombre().equals(nombreProductoSeleccionado)) {
                String estadoActual = producto.isActivo() ? "Activo" : "Inactivo";
                jLabelEstadoActual.setText("Estado actual: " + estadoActual);
                break;
            }
        }
    }

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAplicarActionPerformed
        Producto producto = null;
        String nombreProductoSeleccionado = (String) jComboBoxProductos.getSelectedItem();
        for (Producto p : productos) {
            if (p.getNombre().equals(nombreProductoSeleccionado)) {
                producto = p;
            }
        }

        boolean activar = obtenerEstadoSeleccionado();

        ProductoDAO productoDAO = new ProductoDAO();
        try {
            productoDAO.activarDesactivarProducto(producto.getId(), activar);
            String mensaje = activar ? "Producto activado exitosamente." : "Producto desactivado exitosamente.";
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensaje);
            cargarProductos(); // Recargar la lista de productos para reflejar el cambio
        } catch (SQLException e) {
            String mensajeError = "Error al actualizar el estado del producto: " + e.getMessage();
            MensajeErrorFrame mensajeErrorFrame = new MensajeErrorFrame(null, true, mensajeError);
        }

    }// GEN-LAST:event_jButtonAplicarActionPerformed

    private boolean obtenerEstadoSeleccionado() {
        String estadoSeleccionado = (String) jComboBoxActivarDesactivar.getSelectedItem();
        return "Activar".equals(estadoSeleccionado);
    }

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
        FrameInicioAdministradorSucursal frameInicioAdministradorSucursal = new FrameInicioAdministradorSucursal(
                usuario);
        frameInicioAdministradorSucursal.setVisible(true);
    }// GEN-LAST:event_jButtonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxActivarDesactivar;
    private javax.swing.JComboBox<String> jComboBoxProductos;
    private javax.swing.JLabel jLabelEstadoActual;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
