/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primera_practica_codigo.vista.administrador_sucursal;

import com.mycompany.primera_practica_codigo.modelo.entidades.Sucursal;
import com.mycompany.primera_practica_codigo.modelo.entidades.Usuario;
import com.mycompany.primera_practica_codigo.vista.FrameLogin;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos.FrameActivarDesactivarProducto;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos.FrameBuscadorProducto;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos.FrameEditorProducto;
import com.mycompany.primera_practica_codigo.vista.administrador_sucursal.productos.FrameListaDeProductos;
import com.mysql.cj.x.protobuf.MysqlxNotice.Frame;

/**
 *
 * @author Matul
 */
public class FrameInicioAdministradorSucursal extends javax.swing.JFrame {

    private Usuario usuario;
    private Sucursal sucursal;
    private boolean esEstadisticaPartidasJugadas;
    private boolean esEstadisticaRankingJugadores;

    /**
     * Creates new form FrameInicioAdminstradorSucursal
     */
    public FrameInicioAdministradorSucursal(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        this.sucursal = usuario.getSucursal();
        colocarDatos();
        this.esEstadisticaPartidasJugadas = false;
        this.esEstadisticaRankingJugadores = false;
    }

    private void colocarDatos() {
        jLabelNombreAdmin.setText("Administrador: " + usuario.getNombreUsuario());
        jLabelNombreSucural.setText("Sucursal: " + usuario.getSucursal().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreTycoon = new javax.swing.JLabel();
        jLabelSuperadministrador = new javax.swing.JLabel();
        jLabelNombreAdmin = new javax.swing.JLabel();
        jLabelNombreSucural = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabelProductos = new javax.swing.JLabel();
        jButtonNuevoProducto = new javax.swing.JButton();
        jButtonEditarProducto = new javax.swing.JButton();
        jButtonActivarDesactivar = new javax.swing.JButton();
        jButtonListaProductos = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabelGestionUsuarios = new javax.swing.JLabel();
        jButtonVerPartidasJugadas = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonRakingJugadores = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabelNombreTycoon.setFont(new java.awt.Font("Greconian", 0, 18)); // NOI18N
        jLabelNombreTycoon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreTycoon.setText("Pizza Express Tycoon");
        jPanel2.add(jLabelNombreTycoon);

        jLabelSuperadministrador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelSuperadministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSuperadministrador.setText("Administrador de sucursal");
        jPanel2.add(jLabelSuperadministrador);

        jLabelNombreAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreAdmin.setText("Nombre Administrador");
        jPanel2.add(jLabelNombreAdmin);

        jLabelNombreSucural.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreSucural.setText("Nombre sucursal");
        jPanel2.add(jLabelNombreSucural);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10);

        jPanel9.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

        jLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos.setText("Productos");
        jPanel9.add(jLabelProductos);

        jButtonNuevoProducto.setText("Nuevo Producto");
        jButtonNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoProductoActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonNuevoProducto);

        jButtonEditarProducto.setText("Editar Producto");
        jButtonEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProductoActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonEditarProducto);

        jButtonActivarDesactivar.setText("Activar / Desactivar Producto");
        jButtonActivarDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivarDesactivarActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonActivarDesactivar);

        jButtonListaProductos.setText("Lista Productos");
        jButtonListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaProductosActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonListaProductos);

        jPanel3.add(jPanel9);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13);

        jPanel11.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

        jLabelGestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGestionUsuarios.setText("Estadisticas");
        jPanel11.add(jLabelGestionUsuarios);

        jButtonVerPartidasJugadas.setText("Ver partidas jugadas");
        jButtonVerPartidasJugadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPartidasJugadasActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonVerPartidasJugadas);

        jPanel12.add(jPanel11);

        jPanel14.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ranking ");
        jPanel14.add(jLabel5);

        jButtonRakingJugadores.setText("Ver Ranking Jugadores ");
        jButtonRakingJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRakingJugadoresActionPerformed(evt);
            }
        });
        jPanel14.add(jButtonRakingJugadores);

        jPanel12.add(jPanel14);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel16);

        jPanel1.add(jPanel12);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel4);

        jButtonCerrarSesion.setText("Cerrar Sesion ");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        jPanel20.add(jButtonCerrarSesion);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel5);

        jPanel17.add(jPanel20);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18);

        jPanel1.add(jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNuevoProductoActionPerformed
        FrameEditorProducto frameEditorProducto = new FrameEditorProducto(usuario);
        frameEditorProducto.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonNuevoProductoActionPerformed

    private void jButtonListaProductosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonListaProductosActionPerformed
        FrameListaDeProductos frameListaProductos = new FrameListaDeProductos(usuario);
        frameListaProductos.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonListaProductosActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        this.dispose();
        FrameLogin frameLogin = new FrameLogin();
        frameLogin.setVisible(true);
    }// GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditarProductoActionPerformed
        FrameBuscadorProducto buscadorProducto = new FrameBuscadorProducto(this, this, true, usuario);
        buscadorProducto.setVisible(true);
    }// GEN-LAST:event_jButtonEditarProductoActionPerformed

    private void jButtonActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonActivarDesactivarActionPerformed
        FrameActivarDesactivarProducto frameActivarDesactivarProducto = new FrameActivarDesactivarProducto(usuario);
        frameActivarDesactivarProducto.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonActivarDesactivarActionPerformed

    private void jButtonVerPartidasJugadasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVerPartidasJugadasActionPerformed
        this.dispose();
        this.esEstadisticaPartidasJugadas = true;
        this.esEstadisticaRankingJugadores = false;
        FrameListaExportacion frameLista = new FrameListaExportacion(esEstadisticaPartidasJugadas,
                esEstadisticaRankingJugadores, usuario);
        frameLista.setVisible(true);
    }// GEN-LAST:event_jButtonVerPartidasJugadasActionPerformed

    private void jButtonRakingJugadoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRakingJugadoresActionPerformed
        this.dispose();
        this.esEstadisticaPartidasJugadas = false;
        this.esEstadisticaRankingJugadores = true;
        FrameListaExportacion frameLista = new FrameListaExportacion(esEstadisticaPartidasJugadas,
                esEstadisticaRankingJugadores, usuario);
        frameLista.setVisible(true);
    }// GEN-LAST:event_jButtonRakingJugadoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivarDesactivar;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonEditarProducto;
    private javax.swing.JButton jButtonListaProductos;
    private javax.swing.JButton jButtonNuevoProducto;
    private javax.swing.JButton jButtonRakingJugadores;
    private javax.swing.JButton jButtonVerPartidasJugadas;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelGestionUsuarios;
    private javax.swing.JLabel jLabelNombreAdmin;
    private javax.swing.JLabel jLabelNombreSucural;
    private javax.swing.JLabel jLabelNombreTycoon;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelSuperadministrador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
